name: NanoCore
version: '${project.version}'
main: gg.mc.nanoserver.nanoCore.NanoCore
api-version: '1.20'
author: GloomyCloud
commands:
  거래:
    description: 개인 거래 명령어
    usage: "§c 명령어를 수동으로 실행하지 마세요."
  강화:
    description: 강화 명령어
    usage: /강화

